import json
import random
import re
from telethon import TelegramClient, events
import google.generativeai as genai

# Telegram Bot Credentials
API_ID = 28893110
API_HASH = "f4f5566cfe0e049850db6f2ee412845a"
BOT_TOKEN = "7888406641:AA3BGM18is24cpY"

# Google Gemini API Key
GEMINI_API_KEY = "AIzaSyCWxevdOJ6k6f7gpzTBdHhQ1FsIbsAaVl8"

# Initialize Google Gemini AI
genai.configure(api_key=GEMINI_API_KEY)
MODEL_NAME = "gemini-1.5-pro"
model = genai.GenerativeModel(MODEL_NAME)

# Load responses & bad words from JSON files
with open("responses.json", "r", encoding="utf-8") as file:
    response_data = json.load(file)

with open("badwords.json", "r", encoding="utf-8") as file:
    badword_data = json.load(file)

# Function to check if any 4-character sequence in message matches a bad word
def detect_badword_level(user_message):
    user_message = user_message.lower()
    
    for level in ["high", "medium", "low"]:
        for badword in badword_data[level]:
            badword = badword.lower()
            for i in range(len(badword) - 3):  # Check 4-char sequences
                if badword[i:i+4] in user_message:
                    return level  # Return the matched level
    
    return None  # No bad word found

# Words & phrases to replace AI/Gemini credits
CREDIT_WORDS = {
    r"\bGoogle\b": "KKN",
    r"\bAI\b": "KKN",
    r"\bArtificial Intelligence\b": "KKN",
    r"\bGemini\b": "KKN",
    r"\bGemini AI\b": "KKN",
    r"\bMachine Learning\b": "KKN",
    r"\bDeveloped by Google\b": "Created by KKN",
    r"\bPowered by AI\b": "Powered by KKN",
    r"\bAI-generated\b": "KKN-generated",
    r"\bThis response is generated by\b": "This response is from KKN",
    r"\bI am an AI\b": "I am KKN",
    r"\bI am a chatbot\b": "I am KKN",
    r"\bThis is an AI-generated response\b": "This is a KKN-generated response",
}

# Initialize Telegram Bot
bot = TelegramClient('bot_session', API_ID, API_HASH).start(bot_token=BOT_TOKEN)

@bot.on(events.NewMessage)
async def handle_message(event):
    user_message = event.text.lower()  # Convert to lowercase

    # Check for bad words and get severity level
    badword_level = detect_badword_level(user_message)

    if badword_level:
        # If a bad word is found, respond using local responses.json
        reply_text = random.choice(response_data[badword_level])
    else:
        # If no bad word is found, send the message to Gemini AI
        try:
            response = model.generate_content(user_message)
            if response and response.candidates:
                reply_text = response.candidates[0].content.parts[0].text
            else:
                reply_text = random.choice(response_data["neutral"])  # Neutral response
        except Exception as e:
            reply_text = f"Error: {e}"  # Debugging response

    # Replace AI-related credits with "KKN"
    for pattern, replacement in CREDIT_WORDS.items():
        reply_text = re.sub(pattern, replacement, reply_text, flags=re.IGNORECASE)

    await event.respond(reply_text)

# Start the bot
print("Bot is running...")
bot.run_until_disconnected()
